In [1]:
import pandas as pd

In [2]:
traffic_data = pd.read_excel('../database/traffic_data.xlsx')

In [3]:
traffic_data.shape

(335, 11)

In [4]:
traffic_data.duration.dtype

dtype('int64')

In [5]:
traffic_data.tail()

,id,requestId,departureTime,distance,duration,trafficDuration,destinations,origins,provider,createdAt,updatedAt
330,1968,44,Thu Sep 07 2023 21:00:00 GMT+0000 (Greenwich M...,3.6 km,215,206,"Toyota, Isolo 102214, Ikeja, Lagos, Nigeria","1 Afolabi Lesi St, Ilupeju 102215, Lagos, Nigeria",google,2023-09-07 20:59:54.885,2023-09-07 20:59:54.885
331,1961,46,Thu Sep 07 2023 21:00:00 GMT+0000 (Greenwich M...,5.1 km,298,278,"G84F+456, Itire 102214, Lagos, Nigeria","Toyota, Isolo 102214, Ikeja, Lagos, Nigeria",google,2023-09-07 20:59:54.668,2023-09-07 20:59:54.668
332,1966,48,Thu Sep 07 2023 21:00:00 GMT+0000 (Greenwich M...,5.0 km,339,337,"Fatgbems, Coker 102102, Ikeja, Lagos, Nigeria","G84F+456, Itire 102214, Lagos, Nigeria",google,2023-09-07 20:59:54.831,2023-09-07 20:59:54.831
333,1962,35,Thu Sep 07 2023 21:00:00 GMT+0000 (Greenwich M...,1.8 km,397,274,"P72M+7J9, Kumasi, Ghana","P78G+2VW, Kumasi-Sunyani Rd, Kumasi, Ghana",google,2023-09-07 20:59:54.669,2023-09-07 20:59:54.669
334,1969,41,Thu Sep 07 2023 21:00:00 GMT+0000 (Greenwich M...,19.9 km,1043,1124,"Ibeju Lekki Express Road Lagos, 105101, Lekki,...","Epe, 106101, Epe, Lagos, Nigeria",google,2023-09-07 20:59:54.851,2023-09-07 20:59:54.851

In [6]:
new_traffic = traffic_data.drop("id",axis=1).copy()

In [7]:
new_traffic.head(8)

,requestId,departureTime,distance,duration,trafficDuration,destinations,origins,provider,createdAt,updatedAt
0,9,Thu Sep 07 2023 19:30:00 GMT+0000 (Greenwich M...,6.8 km,865,924,"Mwananchi Relini, Nelson Mandela Rd, Dar es Sa...","RK Plaza, Plot Number 40 at Chang’ombe, Dar es...",google,2023-09-07 19:29:54.710,2023-09-07 19:29:54.710
1,12,Thu Sep 07 2023 19:30:00 GMT+0000 (Greenwich M...,2.9 km,324,307,"Nelson Mandela Rd, Dar es Salaam, Tanzania","RK Plaza, Plot Number 40 at Chang’ombe, Dar es...",google,2023-09-07 19:29:54.840,2023-09-07 19:29:54.840
2,3,Thu Sep 07 2023 19:30:00 GMT+0000 (Greenwich M...,2.3 km,304,266,"Plot 2526 Manzese, Dar es Salaam, Tanzania","BRT Usalama, Morogoro Rd, Dar es Salaam, Tanzania",google,2023-09-07 19:29:55.007,2023-09-07 19:29:55.007
3,13,Thu Sep 07 2023 19:30:00 GMT+0000 (Greenwich M...,2.3 km,229,317,"HPG9+9CP, George Bush Hwy, Mallam, Ghana","HPRJ+8HW, Accra, Ghana",google,2023-09-07 19:29:55.221,2023-09-07 19:29:55.221
4,20,Thu Sep 07 2023 19:30:00 GMT+0000 (Greenwich M...,1.4 km,167,260,"Okponglo Bus Stop, Legon E Rd, Accra, Ghana","318 Legon E Rd, Accra, Ghana",google,2023-09-07 19:29:55.496,2023-09-07 19:29:55.496
5,21,Thu Sep 07 2023 19:30:00 GMT+0000 (Greenwich M...,3.0 km,238,229,"Okponglo Bus Stop, Legon E Rd, Accra, Ghana","Atomic first bus stop after Presec Accra, Accr...",google,2023-09-07 19:29:55.521,2023-09-07 19:29:55.521
6,16,Thu Sep 07 2023 19:30:00 GMT+0000 (Greenwich M...,3.2 km,418,353,"1 Mampon Okai Ave, Lapaz, Ghana","HPRJ+8HW, Accra, Ghana",google,2023-09-07 19:29:55.622,2023-09-07 19:29:55.622
7,18,Thu Sep 07 2023 19:30:00 GMT+0000 (Greenwich M...,9.1 km,763,842,"No. 324 Sankara, Accra - Main Street, Accra, G...","1 Mampon Okai Ave, Lapaz, Ghana",google,2023-09-07 19:29:55.825,2023-09-07 19:29:55.825

In [8]:
new_traffic.requestId.unique()

array([ 9, 12,  3, 13, 20, 21, 16, 18, 30, 31, 26, 27, 23, 24, 29, 28, 22,
       32, 35, 36, 15, 37,  1, 44, 19, 25, 33, 39, 38, 42, 41, 45, 34, 48,
       17,  4, 47, 14, 40, 11,  5,  2, 43,  6, 10, 46,  8,  7])

In [9]:
new_traffic.duration.unique()

array([ 865,  324,  304,  229,  167,  238,  418,  763,  884,  429,  535,
        195,  465,  363,  402,  545,  374,  397,  276,  318, 2069,  394,
        215,  164,  321,  364, 4364, 1554, 1759, 1043, 1934,  383,  339,
        831,  614, 1544,  790, 3495,  718,  571,  768,  985,  702, 1059,
        298,  379,  631,  868,  791,  972,  488])

In [10]:
per_id = new_traffic.groupby("requestId")

In [11]:
per_id.head()

,requestId,departureTime,distance,duration,trafficDuration,destinations,origins,provider,createdAt,updatedAt
0,9,Thu Sep 07 2023 19:30:00 GMT+0000 (Greenwich M...,6.8 km,865,924,"Mwananchi Relini, Nelson Mandela Rd, Dar es Sa...","RK Plaza, Plot Number 40 at Chang’ombe, Dar es...",google,2023-09-07 19:29:54.710,2023-09-07 19:29:54.710
1,12,Thu Sep 07 2023 19:30:00 GMT+0000 (Greenwich M...,2.9 km,324,307,"Nelson Mandela Rd, Dar es Salaam, Tanzania","RK Plaza, Plot Number 40 at Chang’ombe, Dar es...",google,2023-09-07 19:29:54.840,2023-09-07 19:29:54.840
2,3,Thu Sep 07 2023 19:30:00 GMT+0000 (Greenwich M...,2.3 km,304,266,"Plot 2526 Manzese, Dar es Salaam, Tanzania","BRT Usalama, Morogoro Rd, Dar es Salaam, Tanzania",google,2023-09-07 19:29:55.007,2023-09-07 19:29:55.007
3,13,Thu Sep 07 2023 19:30:00 GMT+0000 (Greenwich M...,2.3 km,229,317,"HPG9+9CP, George Bush Hwy, Mallam, Ghana","HPRJ+8HW, Accra, Ghana",google,2023-09-07 19:29:55.221,2023-09-07 19:29:55.221
4,20,Thu Sep 07 2023 19:30:00 GMT+0000 (Greenwich M...,1.4 km,167,260,"Okponglo Bus Stop, Legon E Rd, Accra, Ghana","318 Legon E Rd, Accra, Ghana",google,2023-09-07 19:29:55.496,2023-09-07 19:29:55.496
...,...,...,...,...,...,...,...,...,...,...
235,32,Thu Sep 07 2023 20:30:00 GMT+0000 (Greenwich M...,4.7 km,374,580,"M8X6+97V, Sunyani Rd, Kumasi, Ghana","P922+6RF, Sunyani Rd, Kumasi, Ghana",google,2023-09-07 20:30:04.907,2023-09-07 20:30:04.907
236,30,Thu Sep 07 2023 20:30:00 GMT+0000 (Greenwich M...,6.4 km,884,867,"Suame Roundabout, Kumasi, Ghana","304 Eastern By-Pass, Kumasi, Ghana",google,2023-09-07 20:30:07.547,2023-09-07 20:30:07.547
237,46,Thu Sep 07 2023 20:30:00 GMT+0000 (Greenwich M...,5.1 km,298,282,"G84F+456, Itire 102214, Lagos, Nigeria","Toyota, Isolo 102214, Ikeja, Lagos, Nigeria",google,2023-09-07 20:30:04.154,2023-09-07 20:30:04.154
238,37,Thu Sep 07 2023 20:30:00 GMT+0000 (Greenwich M...,21.6 km,2069,1675,"2 Adetokunbo Ademola Street, Eti-Osa 106104, L...","Ajah, Aja 106104, Lekki, Lagos, Nigeria",google,2023-09-07 20:30:07.624,2023-09-07 20:30:07.624
269,34,Thu Sep 07 2023 20:45:00 GMT+0000 (Greenwich M...,3.0 km,383,938,"P72M+7J9, Kumasi, Ghana","M8X6+97V, Sunyani Rd, Kumasi, Ghana",google,2023-09-07 20:44:56.190,2023-09-07 20:44:56.190

In [12]:
per_id.duration.unique()

requestId
1          [394]
2     [985, 972]
3          [304]
4          [614]
5          [768]
6          [418]
7          [631]
8          [379]
9          [865]
10        [1059]
11         [571]
12         [324]
13         [229]
14    [790, 718]
15         [318]
16         [418]
17    [831, 868]
18         [763]
19         [164]
20         [167]
21         [238]
22         [545]
23         [195]
24         [465]
25         [321]
26    [535, 488]
27         [418]
28         [402]
29         [363]
30         [884]
31         [429]
32         [374]
33         [364]
34         [383]
35         [397]
36         [276]
37        [2069]
38        [1554]
39        [4364]
40        [3495]
41        [1043]
42        [1759]
43    [702, 791]
44         [215]
45        [1934]
46         [298]
47        [1544]
48         [339]
Name: duration, dtype: object

In [13]:
per_id.duration.nunique()

requestId
1     1
2     2
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    1
12    1
13    1
14    2
15    1
16    1
17    2
18    1
19    1
20    1
21    1
22    1
23    1
24    1
25    1
26    2
27    1
28    1
29    1
30    1
31    1
32    1
33    1
34    1
35    1
36    1
37    1
38    1
39    1
40    1
41    1
42    1
43    2
44    1
45    1
46    1
47    1
48    1
Name: duration, dtype: int64

In [14]:
per_id.trafficDuration.unique()

requestId
1            [344, 322, 302, 320, 308, 333, 312]
2            [807, 787, 843, 837, 820, 798, 795]
3                 [266, 256, 254, 262, 268, 249]
4            [513, 493, 503, 514, 510, 502, 500]
5            [603, 596, 587, 569, 600, 555, 553]
6                 [344, 327, 342, 338, 323, 319]
7            [674, 585, 549, 532, 530, 500, 492]
8                 [323, 296, 305, 293, 286, 287]
9           [924, 945, 1107, 954, 803, 757, 660]
10         [1080, 1019, 942, 895, 875, 809, 785]
11           [584, 568, 552, 530, 550, 536, 513]
12           [307, 289, 285, 279, 271, 269, 280]
13           [317, 313, 302, 276, 264, 262, 251]
14           [854, 896, 811, 829, 735, 704, 662]
15           [729, 592, 638, 569, 591, 547, 507]
16           [353, 381, 387, 415, 373, 382, 366]
17         [1158, 1011, 940, 832, 878, 831, 879]
18           [842, 802, 752, 727, 843, 762, 708]
19                     [147, 138, 149, 141, 135]
20           [260, 262, 215, 170, 156, 159, 173]
21                [229, 225, 224, 218, 216, 199]
22           [779, 564, 549, 577, 670, 668, 624]
23                [199, 190, 186, 194, 189, 187]
24           [713, 477, 455, 451, 584, 567, 540]
25           [497, 485, 339, 299, 279, 276, 261]
26           [592, 538, 682, 469, 547, 520, 485]
27           [728, 455, 424, 400, 386, 350, 340]
28           [607, 469, 362, 346, 359, 361, 394]
29           [452, 434, 417, 405, 404, 400, 382]
30          [1353, 961, 861, 841, 867, 781, 803]
31           [464, 445, 466, 479, 473, 481, 501]
32                [706, 613, 610, 599, 580, 548]
33                [387, 396, 376, 358, 348, 336]
34               [849, 1007, 991, 963, 938, 924]
35                     [345, 309, 325, 302, 274]
36                [287, 292, 296, 285, 279, 274]
37    [1820, 1767, 1726, 1725, 1675, 1641, 1660]
38    [2107, 2055, 1762, 1717, 1547, 1413, 1352]
39    [4939, 4575, 4332, 4318, 4129, 4019, 3972]
40    [4116, 4083, 3720, 3582, 3502, 3389, 3184]
41    [1122, 1129, 1193, 1208, 1230, 1131, 1124]
42    [1878, 1857, 1801, 1774, 1752, 1770, 1797]
43           [751, 803, 853, 683, 660, 654, 640]
44                [228, 219, 211, 208, 198, 206]
45          [1773, 1701, 1681, 1655, 1650, 1639]
46                [301, 298, 291, 280, 282, 278]
47    [1420, 1351, 1328, 1275, 1296, 1282, 1284]
48                [348, 344, 345, 339, 346, 337]
Name: trafficDuration, dtype: object

Duraction and trafficaDuration fields are mixed with second values and minutes. Convert seconds to minutes

In [19]:
def convert_to_minutes(secs):
    if 'mins' in str(secs):
        return secs
    minutes = int(secs) // 60
    seconds_remainder = int(secs) % 60
    return f"{minutes} mins {seconds_remainder} secs"

In [20]:
new_traffic["duration_min"] = new_traffic["duration"].apply(convert_to_minutes)

In [ ]:
new_traffic.head()

,requestId,departureTime,distance,duration,trafficDuration,destinations,origins,createdAt,updatedAt,duration_min
0,2,"Tue, 05 Sep 2023 20:20:00 GMT",5.7 km,16 mins,14 mins,"Plot 2526 Manzese, Dar es Salaam, Tanzania","Makaburini Amani House Ubungo Mabibo, Dar es S...",2023-09-05 20:19:56.539,2023-09-05 20:19:56.539,16 mins
1,3,"Tue, 05 Sep 2023 20:20:00 GMT",2.3 km,5 mins,4 mins,"Plot 2526 Manzese, Dar es Salaam, Tanzania","BRT Usalama, Morogoro Rd, Dar es Salaam, Tanzania",2023-09-05 20:19:57.017,2023-09-05 20:19:57.017,5 mins
2,4,"Tue, 05 Sep 2023 20:20:00 GMT",4.2 km,10 mins,8 mins,"BRT Usalama, Morogoro Rd, Dar es Salaam, Tanzania","Plot 2526 Manzese, Dar es Salaam, Tanzania",2023-09-05 20:19:57.156,2023-09-05 20:19:57.156,10 mins
3,1,"Tue, 05 Sep 2023 20:25:00 GMT",2.9 km,7 mins,5 mins,"Makaburini Amani House Ubungo Mabibo, Dar es S...","Plot 2526 Manzese, Dar es Salaam, Tanzania",2023-09-05 20:24:52.779,2023-09-05 20:24:52.779,7 mins
4,3,"Tue, 05 Sep 2023 20:25:00 GMT",2.3 km,5 mins,4 mins,"Plot 2526 Manzese, Dar es Salaam, Tanzania","BRT Usalama, Morogoro Rd, Dar es Salaam, Tanzania",2023-09-05 20:24:52.853,2023-09-05 20:24:52.853,5 mins

In [ ]:
id_groups = new_traffic.groupby("requestId")

In [ ]:
id_groups['duration_min'].unique()

requestId
1                     [7 mins]
2                    [16 mins]
3                     [5 mins]
4                    [10 mins]
5                    [13 mins]
6                     [7 mins]
7                    [10 mins]
8                     [6 mins]
9                    [14 mins]
10                   [18 mins]
11                   [10 mins]
12                    [5 mins]
13                    [4 mins]
14          [13 mins, 12 mins]
15            [6 mins, 5 mins]
16                    [7 mins]
17                   [14 mins]
18                   [13 mins]
19                    [3 mins]
20                    [3 mins]
21                    [4 mins]
22                    [9 mins]
23                    [3 mins]
24                    [8 mins]
25                    [5 mins]
26                    [9 mins]
27                    [7 mins]
28                    [7 mins]
29                    [6 mins]
30                   [15 mins]
31                    [7 mins]
32                    [6 mins]
33                    [6 mins]
34                    [7 mins]
35                    [7 mins]
36                    [5 mins]
37                   [34 mins]
38                   [26 mins]
39            [1 hour 12 mins]
40                   [58 mins]
41                   [17 mins]
42    [1 hour 2 mins, 29 mins]
43                   [12 mins]
44                    [4 mins]
45                   [33 mins]
46                    [5 mins]
47                   [26 mins]
48                    [6 mins]
Name: duration_min, dtype: object

In [ ]:
id_groups['duration_min'].nunique()

requestId
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    1
12    1
13    1
14    2
15    2
16    1
17    1
18    1
19    1
20    1
21    1
22    1
23    1
24    1
25    1
26    1
27    1
28    1
29    1
30    1
31    1
32    1
33    1
34    1
35    1
36    1
37    1
38    1
39    1
40    1
41    1
42    2
43    1
44    1
45    1
46    1
47    1
48    1
Name: duration_min, dtype: int64

In [21]:
new_traffic["t_duration_min"] = new_traffic["trafficDuration"].apply(convert_to_minutes)

In [22]:
id_groups = new_traffic.groupby("requestId")

In [23]:
id_groups['t_duration_min'].unique()

requestId
1     [5 mins 44 secs, 5 mins 22 secs, 5 mins 2 secs...
2     [13 mins 27 secs, 13 mins 7 secs, 14 mins 3 se...
3     [4 mins 26 secs, 4 mins 16 secs, 4 mins 14 sec...
4     [8 mins 33 secs, 8 mins 13 secs, 8 mins 23 sec...
5     [10 mins 3 secs, 9 mins 56 secs, 9 mins 47 sec...
6     [5 mins 44 secs, 5 mins 27 secs, 5 mins 42 sec...
7     [11 mins 14 secs, 9 mins 45 secs, 9 mins 9 sec...
8     [5 mins 23 secs, 4 mins 56 secs, 5 mins 5 secs...
9     [15 mins 24 secs, 15 mins 45 secs, 18 mins 27 ...
10    [18 mins 0 secs, 16 mins 59 secs, 15 mins 42 s...
11    [9 mins 44 secs, 9 mins 28 secs, 9 mins 12 sec...
12    [5 mins 7 secs, 4 mins 49 secs, 4 mins 45 secs...
13    [5 mins 17 secs, 5 mins 13 secs, 5 mins 2 secs...
14    [14 mins 14 secs, 14 mins 56 secs, 13 mins 31 ...
15    [12 mins 9 secs, 9 mins 52 secs, 10 mins 38 se...
16    [5 mins 53 secs, 6 mins 21 secs, 6 mins 27 sec...
17    [19 mins 18 secs, 16 mins 51 secs, 15 mins 40 ...
18    [14 mins 2 secs, 13 mins 22 secs, 12 mins 32 s...
19    [2 mins 27 secs, 2 mins 18 secs, 2 mins 29 sec...
20    [4 mins 20 secs, 4 mins 22 secs, 3 mins 35 sec...
21    [3 mins 49 secs, 3 mins 45 secs, 3 mins 44 sec...
22    [12 mins 59 secs, 9 mins 24 secs, 9 mins 9 sec...
23    [3 mins 19 secs, 3 mins 10 secs, 3 mins 6 secs...
24    [11 mins 53 secs, 7 mins 57 secs, 7 mins 35 se...
25    [8 mins 17 secs, 8 mins 5 secs, 5 mins 39 secs...
26    [9 mins 52 secs, 8 mins 58 secs, 11 mins 22 se...
27    [12 mins 8 secs, 7 mins 35 secs, 7 mins 4 secs...
28    [10 mins 7 secs, 7 mins 49 secs, 6 mins 2 secs...
29    [7 mins 32 secs, 7 mins 14 secs, 6 mins 57 sec...
30    [22 mins 33 secs, 16 mins 1 secs, 14 mins 21 s...
31    [7 mins 44 secs, 7 mins 25 secs, 7 mins 46 sec...
32    [11 mins 46 secs, 10 mins 13 secs, 10 mins 10 ...
33    [6 mins 27 secs, 6 mins 36 secs, 6 mins 16 sec...
34    [14 mins 9 secs, 16 mins 47 secs, 16 mins 31 s...
35    [5 mins 45 secs, 5 mins 9 secs, 5 mins 25 secs...
36    [4 mins 47 secs, 4 mins 52 secs, 4 mins 56 sec...
37    [30 mins 20 secs, 29 mins 27 secs, 28 mins 46 ...
38    [35 mins 7 secs, 34 mins 15 secs, 29 mins 22 s...
39    [82 mins 19 secs, 76 mins 15 secs, 72 mins 12 ...
40    [68 mins 36 secs, 68 mins 3 secs, 62 mins 0 se...
41    [18 mins 42 secs, 18 mins 49 secs, 19 mins 53 ...
42    [31 mins 18 secs, 30 mins 57 secs, 30 mins 1 s...
43    [12 mins 31 secs, 13 mins 23 secs, 14 mins 13 ...
44    [3 mins 48 secs, 3 mins 39 secs, 3 mins 31 sec...
45    [29 mins 33 secs, 28 mins 21 secs, 28 mins 1 s...
46    [5 mins 1 secs, 4 mins 58 secs, 4 mins 51 secs...
47    [23 mins 40 secs, 22 mins 31 secs, 22 mins 8 s...
48    [5 mins 48 secs, 5 mins 44 secs, 5 mins 45 sec...
Name: t_duration_min, dtype: object

In [ ]:
id_groups['t_duration_min'].nunique()

requestId
1     3
2     3
3     2
4     3
5     2
6     2
7     3
8     2
9     2
10    2
11    2
12    1
13    2
14    2
15    3
16    2
17    2
18    3
19    2
20    2
21    2
22    2
23    1
24    3
25    2
26    2
27    2
28    2
29    1
30    2
31    2
32    2
33    2
34    2
35    2
36    1
37    2
38    2
39    2
40    3
41    3
42    2
43    3
44    2
45    2
46    1
47    3
48    2
Name: t_duration_min, dtype: int64